"""
builder.templates
==================

Centralized templates used by the Builder Engine:
    - LLM prompt templates for module/test generation
    - Static fallback templates used only if the LLM is unreachable
      (keeps the Builder resilient / production-safe)
    - The ``prompt.txt`` artifact template saved alongside every
      generated module for traceability/reproducibility.

Keeping templates in one place satisfies the single-responsibility
principle and makes prompt-engineering changes low-risk.
"""

from __future__ import annotations

__all__ = [
    "module_generation_prompt",
    "test_generation_prompt",
    "prompt_artifact",
    "fallback_module_code",
    "fallback_test_code",
    "init_file_content",
]


def module_generation_prompt(module_name: str, context: str = "") -> str:
    """
    Build the LLM prompt used to generate a new module's source code.

    Args:
        module_name: Name of the module to generate (e.g. ``"planner"``).
        context: Optional project context (from ``ContextBuilder``) to
            ground the generation in the existing codebase conventions.

    Returns:
        A complete prompt string ready to send to ``LLMManager``.
    """
    context_block = f"\nProject context:\n{context}\n" if context else ""
    return (
        f"You are a senior Python 3.12 engineer working inside the "
        f"JNAS_AI_CORE codebase.\n"
        f"{context_block}"
        f"Generate the full production-ready source code for a new module "
        f"named `{module_name}`.\n\n"
        f"Requirements:\n"
        f"- File will be saved as `{module_name}/{module_name}.py`.\n"
        f"- Define a primary class named `{module_name.capitalize()}` "
        f"encapsulating the module's responsibility.\n"
        f"- Use Python 3.12, full type hints, docstrings (Google style), "
        f"and structured logging via the `logging` module.\n"
        f"- Follow SOLID principles and keep the class single-purpose.\n"
        f"- Include sensible exception handling; never use bare `except`.\n"
        f"- Do NOT include markdown code fences, explanations, or prose.\n"
        f"- Output ONLY valid, runnable Python source code.\n"
    )


def test_generation_prompt(module_name: str, module_code: str) -> str:
    """
    Build the LLM prompt used to generate a pytest unit-test file for a
    freshly generated module.

    Args:
        module_name: Name of the module under test.
        module_code: The generated source code of the module, used so
            the LLM can produce tests that match the real API surface.

    Returns:
        A complete prompt string ready to send to ``LLMManager``.
    """
    return (
        f"You are a senior Python 3.12 test engineer.\n\n"
        f"Below is the source code of a module named `{module_name}`:\n\n"
        f"{module_code}\n\n"
        f"Write a complete pytest unit-test file for this module.\n\n"
        f"Requirements:\n"
        f"- File will be saved as `{module_name}/test_{module_name}.py`.\n"
        f"- Import the module using `from {module_name}.{module_name} "
        f"import {module_name.capitalize()}` (adjust only if the class "
        f"name in the source differs).\n"
        f"- Cover the main public methods with at least one happy-path "
        f"test and one edge-case/error-handling test.\n"
        f"- Use plain `pytest` (no unittest.TestCase), fixtures where "
        f"appropriate, and clear assertion messages.\n"
        f"- Do NOT include markdown code fences, explanations, or prose.\n"
        f"- Output ONLY valid, runnable Python test code.\n"
    )


def prompt_artifact(module_name: str, generation_prompt: str) -> str:
    """
    Build the content persisted to a generated module's ``prompt.txt``.

    This preserves an audit trail of exactly what was asked of the LLM,
    enabling reproducibility and debugging of generated modules.

    Args:
        module_name: Name of the generated module.
        generation_prompt: The exact prompt sent to the LLM.

    Returns:
        Text content to write to ``prompt.txt``.
    """
    return (
        f"# Build Prompt: {module_name}\n"
        f"# Generated by Builder Engine v1 (JNAS_AI_CORE)\n\n"
        f"{generation_prompt}\n"
    )


def fallback_module_code(module_name: str) -> str:
    """
    Minimal, safe fallback module source used only if LLM generation
    fails outright, so the Builder still produces a working skeleton.

    Args:
        module_name: Name of the module to generate.

    Returns:
        Valid Python source code implementing a minimal class skeleton.
    """
    class_name = module_name.capitalize()
    return (
        f'"""Auto-generated skeleton module for `{module_name}`.\n\n'
        f"This fallback was created because LLM-based generation was "
        f'unavailable or failed. Replace with real logic.\n"""\n\n'
        f"from __future__ import annotations\n\n"
        f"import logging\n"
        f"from typing import Any\n\n"
        f"logger = logging.getLogger(__name__)\n\n\n"
        f"class {class_name}:\n"
        f'    """Skeleton implementation for the `{module_name}` module."""\n\n'
        f"    def __init__(self) -> None:\n"
        f'        """Initialize the {class_name}."""\n'
        f"        logger.debug(\"%s initialized\", self.__class__.__name__)\n\n"
        f"    def run(self, *args: Any, **kwargs: Any) -> Any:\n"
        f'        """Execute the primary responsibility of this module.\n\n'
        f"        Raises:\n"
        f"            NotImplementedError: Always, until implemented.\n"
        f'        """\n'
        f'        raise NotImplementedError("{class_name}.run is not yet implemented.")\n'
    )


def fallback_test_code(module_name: str) -> str:
    """
    Minimal, safe fallback pytest file used only if LLM test generation
    fails outright.

    Args:
        module_name: Name of the module under test.

    Returns:
        Valid pytest source code with a basic smoke test.
    """
    class_name = module_name.capitalize()
    return (
        f'"""Auto-generated fallback tests for `{module_name}`."""\n\n'
        f"import pytest\n\n"
        f"from {module_name}.{module_name} import {class_name}\n\n\n"
        f"def test_instantiation() -> None:\n"
        f'    """The module class should instantiate without error."""\n'
        f"    instance = {class_name}()\n"
        f"    assert instance is not None\n\n\n"
        f"def test_run_raises_not_implemented() -> None:\n"
        f'    """Skeleton run() should raise until implemented."""\n'
        f"    instance = {class_name}()\n"
        f"    with pytest.raises(NotImplementedError):\n"
        f"        instance.run()\n"
    )


def init_file_content(module_name: str) -> str:
    """
    Build the content of a generated module's ``__init__.py``.

    Args:
        module_name: Name of the module package.

    Returns:
        Text content for ``__init__.py``.
    """
    class_name = module_name.capitalize()
    return (
        f'"""{module_name} package (auto-generated by Builder Engine v1)."""\n\n'
        f"from .{module_name} import {class_name}\n\n"
        f'__all__ = ["{class_name}"]\n'
    )
